# Generated by Django 3.2.3 on 2021-06-02 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='person_id',
            new_name='person',
        ),
    ]
